
// lib/debug/scene_test_data.dart

const List<Map<String, dynamic>> kTestScenes = [
  {
    "location": "beach",
    "locationDetails": "tropical island beach, white sand, turquoise water, palm trees",
    "timeOfDay": "afternoon",
    "pose": "dynamic",
    "activity": "running toward the water",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she pulls user by the hand toward the waves, laughing excitedly",
    "intimacyLevel": 0,
    "confidence": 0.9,
  },
  {
    "location": "beach",
    "locationDetails": "golden sand beach at sunset",
    "timeOfDay": "sunset",
    "pose": "walking",
    "activity": "walking together the shoreline",
    "clothingState": "bikini",
    "clothingDetails": 'yellow bikini',
    "charactersPositioning": "holding user's hand tightly while walking together",
    "intimacyLevel": 1,
    "confidence": 0.8,
  },
  {
    "location": "luxury bedroom",
    "locationDetails": "dimly lit bedroom with large bed and silk sheets",
    "timeOfDay": "evening",
    "pose": "kneeling",
    "activity": "performing oral sex",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "kneeling in front of the user, taking his cock into her mouth with eye contact",
    "intimacyLevel": 3,
    "confidence": 0.95,
  },
  {
    "location": "cozy cafe",
    "locationDetails": "romantic cafe with wooden tables and soft lighting",
    "timeOfDay": "afternoon",
    "pose": "sitting",
    "activity": "talking",
    "clothingState": "fully_dressed",
    "clothingDetails": "elegant summer dress",
    "charactersPositioning": "sitting across from the user, holding his hand on the table and smiling warmly",
    "intimacyLevel": 1,
    "confidence": 0.85,
  },
  {
    "location": "city street",
    "locationDetails": "quiet outdoor path with small stones heading toward a museum",
    "timeOfDay": "afternoon",
    "pose": "standing",
    "activity": "walking ahead",
    "clothingState": "fully_dressed",
    "clothingDetails": "casual outfit, sneakers",
    "charactersPositioning": "she faces user briefly, then turns away, walking ahead",
    "intimacyLevel": 0,
    "confidence": 0.8,
  },
  {
    "location": "balcony",
    "locationDetails": "high-rise balcony overlooking the city at night",
    "timeOfDay": "night",
    "pose": "standing",
    "activity": "embracing",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she hugs the user from behind, her arms wrapped around his waist",
    "intimacyLevel": 2,
    "confidence": 0.9,
  },
  {
    "location": "forest",
    "locationDetails": "sunlit forest path with tall trees",
    "timeOfDay": "morning",
    "pose": "standing",
    "activity": "playful interaction",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she jumps into the user's arms, wrapping her legs around his waist",
    "intimacyLevel": 2,
    "confidence": 0.85,
  },
  {
    "location": "luxury hotel room",
    "locationDetails": "elegant hotel suite with king size bed",
    "timeOfDay": "evening",
    "pose": "standing",
    "activity": "passionate moment",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she pushes the user against the wall and kisses his neck",
    "intimacyLevel": 3,
    "confidence": 0.9,
  },
  {
    "location": "bedroom",
    "locationDetails": "soft lighting, messy bed",
    "timeOfDay": "night",
    "pose": "kneeling",
    "activity": "giving blowjob",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "on her knees giving the user a blowjob, looking up seductively",
    "intimacyLevel": 3,
    "confidence": 0.95,
  },
  {
    "location": "park bench",
    "locationDetails": "quiet park with blooming flowers",
    "timeOfDay": "evening",
    "pose": "sitting",
    "activity": "sitting together",
    "clothingState": "fully_dressed",
    "clothingDetails": "light summer dress",
    "charactersPositioning": "she sits on the user's lap, wrapping her arms around his neck",
    "intimacyLevel": 2,
    "confidence": 0.8,
  },
  {
    "location": "dance floor",
    "locationDetails": "dimly lit club with colorful lights",
    "timeOfDay": "night",
    "pose": "dancing",
    "activity": "slow dancing",
    "clothingState": "fully_dressed",
    "clothingDetails": "elegant black dress",
    "charactersPositioning": "dancing closely with the user, bodies pressed together",
    "intimacyLevel": 2,
    "confidence": 0.85,
  },
    {
      "location": "swimming pool",
      "locationDetails": "private outdoor infinity pool at sunset",
      "timeOfDay": "sunset",
      "pose": "dynamic",
      "activity": "playing in water",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she drags the user by the wrist into the pool, both laughing",
      "intimacyLevel": 1
    },
    {
      "location": "kitchen",
      "locationDetails": "modern kitchen with marble countertops",
      "timeOfDay": "evening",
      "pose": "standing",
      "activity": "cooking together",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she stands behind the user and hugs him while he cooks",
      "intimacyLevel": 1
    },
    {
      "location": "car interior",
      "locationDetails": "luxury car at night, city lights visible",
      "timeOfDay": "night",
      "pose": "sitting",
      "activity": "passionate kissing",
      "clothingState": "partially dressed",
      "clothingDetails": "unbuttoned blouse",
      "charactersPositioning": "she climbs onto the user's lap in the driver's seat",
      "intimacyLevel": 3
    },
    {
      "location": "shower",
      "locationDetails": "luxurious glass shower with steam",
      "timeOfDay": "evening",
      "pose": "standing",
      "activity": "showering together",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she presses her body against the user under the running water",
      "intimacyLevel": 2
    },
    {
      "location": "living room",
      "locationDetails": "cozy living room with fireplace",
      "timeOfDay": "night",
      "pose": "sitting",
      "activity": "watching movie",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she cuddles up to the user on the couch, head on his chest",
      "intimacyLevel": 1
    },
    {
      "location": "mountain viewpoint",
      "locationDetails": "scenic mountain overlook at sunset",
      "timeOfDay": "sunset",
      "pose": "standing",
      "activity": "admiring the view",
      "clothingState": "fully_dressed",
      "clothingDetails": "light jacket and jeans",
      "charactersPositioning": "she takes user's hand and leans her head on his shoulder",
      "intimacyLevel": 1
    },
    {
      "location": "bedroom",
      "locationDetails": "romantic bedroom with candles",
      "timeOfDay": "night",
      "pose": "lying",
      "activity": "intimate moment",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she straddles the user, looking down at him seductively",
      "intimacyLevel": 3
    },
    {
      "location": "street",
      "locationDetails": "quiet evening street with street lamps",
      "timeOfDay": "evening",
      "pose": "walking",
      "activity": "walking together",
      "clothingState": "fully_dressed",
      "clothingDetails": "casual outfit",
      "charactersPositioning": "she links her arm with the user's while walking",
      "intimacyLevel": 1
    },
    {
      "location": "office",
      "locationDetails": "modern office after hours",
      "timeOfDay": "night",
      "pose": "standing",
      "activity": "flirting",
      "clothingState": "fully_dressed",
      "clothingDetails": "tight blouse and pencil skirt",
      "charactersPositioning": "she pushes the user against the desk and kisses him",
      "intimacyLevel": 2
    },
    {
      "location": "beach",
      "locationDetails": "secluded beach at night",
      "timeOfDay": "night",
      "pose": "standing",
      "activity": "playing in waves",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she splashes water at the user and then runs into his arms",
      "intimacyLevel": 1
    },
    {
      "location": "gym",
      "locationDetails": "home gym with mirrors",
      "timeOfDay": "morning",
      "pose": "standing",
      "activity": "working out",
      "clothingState": "sportswear",
      "clothingDetails": "tight yoga pants and sports bra",
      "charactersPositioning": "she stands very close to the user, guiding his form",
      "intimacyLevel": 1
    },
    {
      "location": "library",
      "locationDetails": "quiet home library with bookshelves",
      "timeOfDay": "evening",
      "pose": "standing",
      "activity": "reaching for a book",
      "clothingState": "fully_dressed",
      "clothingDetails": "cozy sweater and skirt",
      "charactersPositioning": "she reaches for a high shelf, pressing her body against the user",
      "intimacyLevel": 1
    },
    {
      "location": "hot tub",
      "locationDetails": "outdoor hot tub under the stars",
      "timeOfDay": "night",
      "pose": "sitting",
      "activity": "relaxing in water",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she sits between the user's legs in the hot tub",
      "intimacyLevel": 2
    },
    {
      "location": "meadow",
      "locationDetails": "sunny flower meadow",
      "timeOfDay": "afternoon",
      "pose": "lying",
      "activity": "picnic",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she lies on top of the user, kissing him softly",
      "intimacyLevel": 2
    },
    {
      "location": "elevator",
      "locationDetails": "luxury hotel elevator",
      "timeOfDay": "night",
      "pose": "standing",
      "activity": "intimate moment",
      "clothingState": "fully_dressed",
      "clothingDetails": "evening dress",
      "charactersPositioning": "she pins the user against the wall and kisses him passionately",
      "intimacyLevel": 3
    },
    {
      "location": "kitchen",
      "locationDetails": "modern kitchen island",
      "timeOfDay": "evening",
      "pose": "standing",
      "activity": "flirting",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she sits on the kitchen counter and pulls the user between her legs",
      "intimacyLevel": 3
    },
    {
      "location": "art gallery",
      "locationDetails": "quiet contemporary art gallery",
      "timeOfDay": "afternoon",
      "pose": "standing",
      "activity": "viewing artwork",
      "clothingState": "fully_dressed",
      "clothingDetails": "stylish dress",
      "charactersPositioning": "she stands close behind the user, whispering in his ear",
      "intimacyLevel": 1
    },
    {
      "location": "bedroom",
      "locationDetails": "bedroom with city view",
      "timeOfDay": "night",
      "pose": "standing",
      "activity": "undressing",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she slowly undresses the user while maintaining eye contact",
      "intimacyLevel": 3
    },
    {
      "location": "restaurant",
      "locationDetails": "elegant rooftop restaurant with city view",
      "timeOfDay": "evening",
      "pose": "sitting",
      "activity": "having dinner",
      "clothingState": "fully_dressed",
      "clothingDetails": "black evening dress",
      "charactersPositioning": "sitting at the table opposite the user, gently touching his hand",
      "intimacyLevel": 1
    },
    {
      "location": "art studio",
      "locationDetails": "bright art studio with large windows",
      "timeOfDay": "morning",
      "pose": "standing",
      "activity": "painting",
      "clothingState": "partially_dressed",
      "clothingDetails": "oversized shirt, no pants",
      "charactersPositioning": "standing close behind the user, guiding his hand while painting",
      "intimacyLevel": 1
    },
    {
      "location": "bookstore",
      "locationDetails": "cozy bookstore with wooden shelves",
      "timeOfDay": "afternoon",
      "pose": "standing",
      "activity": "browsing books",
      "clothingState": "fully_dressed",
      "clothingDetails": "cozy sweater and jeans",
      "charactersPositioning": "standing very close to the user between the shelves",
      "intimacyLevel": 1
    },
    {
      "location": "yacht deck",
      "locationDetails": "luxury yacht on the open sea",
      "timeOfDay": "afternoon",
      "pose": "standing",
      "activity": "enjoying the view",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she stands next to the user, leaning slightly against his shoulder",
      "intimacyLevel": 1
    },
    {
      "location": "cinema",
      "locationDetails": "dark movie theater, last row",
      "timeOfDay": "evening",
      "pose": "sitting",
      "activity": "watching movie",
      "clothingState": "fully_dressed",
      "clothingDetails": "casual outfit",
      "charactersPositioning": "sitting beside the user, resting her head on his shoulder",
      "intimacyLevel": 2
    },
    {
      "location": "garden",
      "locationDetails": "beautiful rose garden",
      "timeOfDay": "morning",
      "pose": "standing",
      "activity": "walking",
      "clothingState": "fully_dressed",
      "clothingDetails": "light floral dress",
      "charactersPositioning": "walking side by side with the user, arms brushing",
      "intimacyLevel": 1
    },
    {
      "location": "spa room",
      "locationDetails": "private spa with massage table",
      "timeOfDay": "evening",
      "pose": "lying",
      "activity": "relaxing",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "lying on the massage table while the user stands beside her",
      "intimacyLevel": 2
    },
    {
      "location": "rooftop terrace",
      "locationDetails": "modern rooftop terrace with pool",
      "timeOfDay": "night",
      "pose": "standing",
      "activity": "looking at the city",
      "clothingState": "partially_dressed",
      "clothingDetails": "silk robe",
      "charactersPositioning": "standing in front of the user, facing him closely",
      "intimacyLevel": 2
    },
    {
      "location": "library",
      "locationDetails": "grand old library with ladders",
      "timeOfDay": "afternoon",
      "pose": "standing",
      "activity": "reaching for books",
      "clothingState": "fully_dressed",
      "clothingDetails": "elegant blouse and skirt",
      "charactersPositioning": "she reaches high shelf, pressing back against the user",
      "intimacyLevel": 2
    },
    {
      "location": "picnic spot",
      "locationDetails": "grassy hill with blanket",
      "timeOfDay": "afternoon",
      "pose": "sitting",
      "activity": "picnic",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "sitting on the blanket facing the user, feeding him fruit",
      "intimacyLevel": 2
    },
    {
      "location": "snowy mountain cabin",
      "locationDetails": "warm wooden cabin interior",
      "timeOfDay": "night",
      "pose": "sitting",
      "activity": "by the fireplace",
      "clothingState": "partially_dressed",
      "clothingDetails": "warm sweater only",
      "charactersPositioning": "sitting on the floor between the user's legs",
      "intimacyLevel": 2
    },
    {
      "location": "museum hall",
      "locationDetails": "quiet contemporary art museum",
      "timeOfDay": "afternoon",
      "pose": "standing",
      "activity": "viewing exhibits",
      "clothingState": "fully_dressed",
      "clothingDetails": "stylish coat and dress",
      "charactersPositioning": "standing right next to the user, whispering comments",
      "intimacyLevel": 1
    },
    {
      "location": "tropical waterfall",
      "locationDetails": "hidden waterfall in jungle",
      "timeOfDay": "afternoon",
      "pose": "standing",
      "activity": "under the waterfall",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "standing under the waterfall with the user",
      "intimacyLevel": 2
    },
    {
      "location": "office desk",
      "locationDetails": "modern home office",
      "timeOfDay": "evening",
      "pose": "sitting",
      "activity": "working",
      "clothingState": "partially_dressed",
      "clothingDetails": "white shirt unbuttoned",
      "charactersPositioning": "sitting on the edge of the desk in front of the user",
      "intimacyLevel": 3
    },
    {
      "location": "vineyard",
      "locationDetails": "sunny vineyard rows",
      "timeOfDay": "morning",
      "pose": "standing",
      "activity": "tasting wine",
      "clothingState": "fully_dressed",
      "clothingDetails": "summer dress and hat",
      "charactersPositioning": "standing close, offering the user a glass of wine",
      "intimacyLevel": 1
    },
    {
      "location": "train compartment",
      "locationDetails": "luxury night train private cabin",
      "timeOfDay": "night",
      "pose": "sitting",
      "activity": "traveling",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "sitting opposite the user with legs touching",
      "intimacyLevel": 2
    },
    {
      "location": "botanical garden",
      "locationDetails": "lush indoor botanical garden",
      "timeOfDay": "afternoon",
      "pose": "standing",
      "activity": "walking",
      "clothingState": "fully_dressed",
      "clothingDetails": "light dress",
      "charactersPositioning": "walking a few steps ahead of the user, turning back to smile",
      "intimacyLevel": 0
    },
    {
      "location": "bedroom",
      "locationDetails": "minimalist modern bedroom",
      "timeOfDay": "morning",
      "pose": "standing",
      "activity": "stretching",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "standing alone near the window, morning light on her body",
      "intimacyLevel": 0
    },
    {
      "location": "cafe terrace",
      "locationDetails": "street cafe terrace",
      "timeOfDay": "morning",
      "pose": "sitting",
      "activity": "drinking coffee",
      "clothingState": "fully_dressed",
      "clothingDetails": "casual chic outfit",
      "charactersPositioning": "sitting alone at the table, looking thoughtful",
      "intimacyLevel": 0
    },
    {
      "location": "lake pier",
      "locationDetails": "wooden pier over calm lake",
      "timeOfDay": "sunset",
      "pose": "standing",
      "activity": "looking at water",
      "clothingState": "fully_dressed",
      "clothingDetails": "light cardigan and dress",
      "charactersPositioning": "standing alone at the end of the pier",
      "intimacyLevel": 0
    },
    {
      "location": "dance studio",
      "locationDetails": "mirrored dance studio",
      "timeOfDay": "evening",
      "pose": "dancing",
      "activity": "practicing dance",
      "clothingState": "partially_dressed",
      "clothingDetails": "leotard and leg warmers",
      "charactersPositioning": "practicing dance moves alone in front of mirror",
      "intimacyLevel": 0
    },
    {
      "location": "kitchen",
      "locationDetails": "bright modern kitchen",
      "timeOfDay": "morning",
      "pose": "standing",
      "activity": "cooking",
      "clothingState": "partially_dressed",
      "clothingDetails": "apron only",
      "charactersPositioning": "standing alone cooking breakfast",
      "intimacyLevel": 0
    },
    {
      "location": "beach",
      "locationDetails": "secluded rocky beach",
      "timeOfDay": "morning",
      "pose": "sitting",
      "activity": "reading book",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "sitting alone on a rock, reading",
      "intimacyLevel": 0
    },
    {
      "location": "luxury car",
      "locationDetails": "inside luxury convertible car",
      "timeOfDay": "afternoon",
      "pose": "sitting",
      "activity": "driving",
      "clothingState": "fully_dressed",
      "clothingDetails": "sunglasses and summer outfit",
      "charactersPositioning": "sitting in the driver's seat alone",
      "intimacyLevel": 0
    },
    {
      "location": "meadow",
      "locationDetails": "wide flower meadow",
      "timeOfDay": "afternoon",
      "pose": "lying",
      "activity": "relaxing",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "lying alone in the grass, enjoying sunlight",
      "intimacyLevel": 0
    },
    {
      "location": "balcony",
      "locationDetails": "hotel balcony with ocean view",
      "timeOfDay": "morning",
      "pose": "standing",
      "activity": "drinking coffee",
      "clothingState": "partially_dressed",
      "clothingDetails": "silk robe",
      "charactersPositioning": "standing alone on the balcony",
      "intimacyLevel": 0
    },
    {
      "location": "gym",
      "locationDetails": "private home gym",
      "timeOfDay": "morning",
      "pose": "standing",
      "activity": "yoga",
      "clothingState": "sportswear",
      "clothingDetails": "yoga outfit",
      "charactersPositioning": "doing yoga alone on the mat",
      "intimacyLevel": 0
    },
    {
      "location": "bathroom",
      "locationDetails": "luxurious marble bathroom",
      "timeOfDay": "evening",
      "pose": "standing",
      "activity": "applying makeup",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "standing alone in front of mirror",
      "intimacyLevel": 0
    },
    {
      "location": "park",
      "locationDetails": "autumn park with fallen leaves",
      "timeOfDay": "afternoon",
      "pose": "walking",
      "activity": "walking",
      "clothingState": "fully_dressed",
      "clothingDetails": "coat and scarf",
      "charactersPositioning": "walking alone along the path",
      "intimacyLevel": 0
    },
    {
      "location": "attic",
      "locationDetails": "cozy attic room with skylight",
      "timeOfDay": "evening",
      "pose": "sitting",
      "activity": "reading by window",
      "clothingState": "partially_dressed",
      "clothingDetails": "oversized sweater",
      "charactersPositioning": "sitting alone by the window with a book",
      "intimacyLevel": 0
    }

];