
const List<Map<String, dynamic>> xTestScenes = [
  {
    "location": "bedroom",
    "locationDetails": "dimly lit luxury bedroom with large bed and mirrors",
    "timeOfDay": "night",
    "pose": "missionary",
    "activity": "receiving deep vaginal penetration",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she lies on her back with legs spread wide, user on top thrusting deeply inside her",
    "intimacyLevel": 3
  },
  {
    "location": "bedroom",
    "locationDetails": "modern bedroom with red lighting",
    "timeOfDay": "night",
    "pose": "doggy_style",
    "activity": "receiving anal sex from behind",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she is on all fours, user behind her penetrating her anus",
    "intimacyLevel": 3
  },
  {
    "location": "hotel_room",
    "locationDetails": "luxury hotel suite with king bed",
    "timeOfDay": "night",
    "pose": "cowgirl",
    "activity": "riding user intensely",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she is on top of user, riding his cock, hands on his chest",
    "intimacyLevel": 3
  },
  {
    "location": "living_room",
    "locationDetails": "luxury living room with sofa",
    "timeOfDay": "night",
    "pose": "bent_over",
    "activity": "bent over sofa receiving sex",
    "clothingState": "partially_dressed",
    "clothingDetails": "skirt lifted, no panties",
    "charactersPositioning": "she is bent over the sofa, user fucking her from behind",
    "intimacyLevel": 3
  },
  {
    "location": "bedroom",
    "locationDetails": "bedroom with silk sheets",
    "timeOfDay": "night",
    "pose": "kneeling",
    "activity": "giving blowjob",
    "clothingState": "lingerie",
    "clothingDetails": "black lace lingerie, stockings",
    "charactersPositioning": "she is kneeling in front of user, sucking his cock",
    "intimacyLevel": 3
  },
  {
    "location": "shower",
    "locationDetails": "steamy glass shower cabin",
    "timeOfDay": "night",
    "pose": "standing",
    "activity": "standing sex against wall",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she is pressed against the shower wall, leg raised, user penetrating her",
    "intimacyLevel": 3
  },
  {
    "location": "bedroom",
    "locationDetails": "bedroom with candles",
    "timeOfDay": "night",
    "pose": "missionary",
    "activity": "legs wrapped around partner",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she lies on back, legs tightly wrapped around user, scratching his back",
    "intimacyLevel": 3
  },
  {
    "location": "office",
    "locationDetails": "luxury home office with desk",
    "timeOfDay": "night",
    "pose": "on_desk",
    "activity": "sex on the desk",
    "clothingState": "partially_dressed",
    "clothingDetails": "unbuttoned blouse, skirt around waist",
    "charactersPositioning": "she sits on the desk with legs spread, user standing between them thrusting",
    "intimacyLevel": 3
  },
  {
    "location": "bedroom",
    "locationDetails": "bedroom with large mirror",
    "timeOfDay": "night",
    "pose": "reverse_cowgirl",
    "activity": "riding user facing away",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she is riding user in reverse cowgirl position, facing away",
    "intimacyLevel": 3
  },
  {
    "location": "balcony",
    "locationDetails": "private hotel balcony at night",
    "timeOfDay": "night",
    "pose": "standing",
    "activity": "standing sex from behind",
    "clothingState": "partially_dressed",
    "clothingDetails": "dress pulled down to waist",
    "charactersPositioning": "she is bent over balcony railing, user taking her from behind",
    "intimacyLevel": 3
  },
  {
    "location": "bedroom",
    "locationDetails": "dimly lit bedroom",
    "timeOfDay": "night",
    "pose": "spooning",
    "activity": "spooning sex",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she lies on side, user behind her penetrating while spooning",
    "intimacyLevel": 3
  },
  {
    "location": "kitchen",
    "locationDetails": "modern kitchen with island",
    "timeOfDay": "night",
    "pose": "bent_over",
    "activity": "sex on kitchen island",
    "clothingState": "lingerie",
    "clothingDetails": "red lace bodysuit pulled aside",
    "charactersPositioning": "she is bent over kitchen island, user fucking her from behind",
    "intimacyLevel": 3
  },
  {
    "location": "bedroom",
    "locationDetails": "bedroom with pillows",
    "timeOfDay": "night",
    "pose": "on_all_fours",
    "activity": "anal sex with fingers",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she is on all fours, user penetrating her anus while she fingers herself",
    "intimacyLevel": 3
  },
  {
    "location": "living_room",
    "locationDetails": "cozy living room with fireplace",
    "timeOfDay": "night",
    "pose": "sitting",
    "activity": "riding in lap",
    "clothingState": "partially_dressed",
    "clothingDetails": "open robe only",
    "charactersPositioning": "she is sitting on user's lap facing him, riding his cock",
    "intimacyLevel": 3
  },
  {
    "location": "bedroom",
    "locationDetails": "bedroom with silk sheets",
    "timeOfDay": "night",
    "pose": "missionary",
    "activity": "deep penetration with eye contact",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she lies on back looking into user's eyes while he thrusts deeply",
    "intimacyLevel": 3
  },
  {
    "location": "bathroom",
    "locationDetails": "luxury bathroom with large bathtub",
    "timeOfDay": "night",
    "pose": "in_bathtub",
    "activity": "sex in bathtub",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she is in the bathtub, legs on user's shoulders while he penetrates her",
    "intimacyLevel": 3
  },
  {
    "location": "bedroom",
    "locationDetails": "bedroom",
    "timeOfDay": "night",
    "pose": "69_position",
    "activity": "mutual oral sex",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she is in 69 position on top of user, sucking his cock while he licks her",
    "intimacyLevel": 3
  },
  {
    "location": "hotel_room",
    "locationDetails": "luxury hotel room",
    "timeOfDay": "night",
    "pose": "standing",
    "activity": "lifted sex",
    "clothingState": "partially_dressed",
    "clothingDetails": "dress around waist",
    "charactersPositioning": "user holds her up against the wall, her legs around his waist",
    "intimacyLevel": 3
  },
  {
    "location": "bedroom",
    "locationDetails": "bedroom with big bed",
    "timeOfDay": "night",
    "pose": "kneeling",
    "activity": "giving deepthroat",
    "clothingState": "lingerie",
    "clothingDetails": "black lace bra and garter belt",
    "charactersPositioning": "she is kneeling, deepthroating the user",
    "intimacyLevel": 3
  },
  {
    "location": "bedroom",
    "locationDetails": "intimate bedroom",
    "timeOfDay": "night",
    "pose": "missionary",
    "activity": "legs over shoulders",
    "clothingState": "nude",
    "clothingDetails": null,
    "charactersPositioning": "she lies on back with legs over user's shoulders, deep penetration",
    "intimacyLevel": 3
  },
    {
      "location": "bedroom",
      "locationDetails": "luxury bedroom with four-poster bed and candles",
      "timeOfDay": "night",
      "pose": "missionary",
      "activity": "deep vaginal sex with intense eye contact",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she lies on her back, legs wide open, user thrusting deeply while looking into her eyes",
      "intimacyLevel": 3
    },
    {
      "location": "hotel_suite",
      "locationDetails": "penthouse suite with floor-to-ceiling windows",
      "timeOfDay": "night",
      "pose": "doggy_style",
      "activity": "hard anal sex from behind",
      "clothingState": "partially_dressed",
      "clothingDetails": "stockings and high heels only",
      "charactersPositioning": "she is on all fours on the bed, user pounding her ass hard",
      "intimacyLevel": 3
    },
    {
      "location": "living_room",
      "locationDetails": "modern living room with leather couch",
      "timeOfDay": "night",
      "pose": "cowgirl",
      "activity": "riding user passionately",
      "clothingState": "lingerie",
      "clothingDetails": "red lace bra pulled down",
      "charactersPositioning": "she straddles the user on the couch, riding his cock wildly",
      "intimacyLevel": 3
    },
    {
      "location": "kitchen",
      "locationDetails": "luxury kitchen with marble island",
      "timeOfDay": "night",
      "pose": "bent_over",
      "activity": "sex from behind on kitchen island",
      "clothingState": "partially_dressed",
      "clothingDetails": "apron only, bottom naked",
      "charactersPositioning": "she is bent over the kitchen island, user fucking her from behind",
      "intimacyLevel": 3
    },
    {
      "location": "bathroom",
      "locationDetails": "luxurious marble bathroom with large mirror",
      "timeOfDay": "night",
      "pose": "standing",
      "activity": "sex in front of mirror",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she stands bent over the sink, user taking her from behind while they watch in mirror",
      "intimacyLevel": 3
    },
    {
      "location": "car",
      "locationDetails": "luxury car parked in secluded spot at night",
      "timeOfDay": "night",
      "pose": "lap_sex",
      "activity": "riding user in car seat",
      "clothingState": "partially_dressed",
      "clothingDetails": "dress pulled up to waist",
      "charactersPositioning": "she is on top of user in the driver seat, riding him",
      "intimacyLevel": 3
    },
    {
      "location": "balcony",
      "locationDetails": "high-rise apartment balcony overlooking city",
      "timeOfDay": "night",
      "pose": "standing",
      "activity": "standing sex against railing",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she grips the railing, user fucking her from behind",
      "intimacyLevel": 3
    },
    {
      "location": "bedroom",
      "locationDetails": "bedroom with big bed and dim lights",
      "timeOfDay": "night",
      "pose": "facesitting",
      "activity": "facesitting and oral",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she sits on user's face, grinding while he licks her pussy",
      "intimacyLevel": 3
    },
    {
      "location": "sauna",
      "locationDetails": "private wooden sauna with heat",
      "timeOfDay": "evening",
      "pose": "sitting",
      "activity": "riding in sauna",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she sits on user facing him, riding slowly in the hot sauna",
      "intimacyLevel": 3
    },
    {
      "location": "bedroom",
      "locationDetails": "bedroom with pillows everywhere",
      "timeOfDay": "night",
      "pose": "spooning",
      "activity": "gentle anal spooning",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she lies on her side, user behind her slowly penetrating her ass",
      "intimacyLevel": 3
    },
    {
      "location": "office",
      "locationDetails": "boss office with large desk",
      "timeOfDay": "night",
      "pose": "on_desk",
      "activity": "sex on office desk",
      "clothingState": "partially_dressed",
      "clothingDetails": "blouse open, skirt around hips",
      "charactersPositioning": "she lies on her back on the desk, legs spread, user thrusting inside her",
      "intimacyLevel": 3
    },
    {
      "location": "bedroom",
      "locationDetails": "bedroom",
      "timeOfDay": "night",
      "pose": "kneeling",
      "activity": "titjob and blowjob",
      "clothingState": "lingerie",
      "clothingDetails": "black lace bra",
      "charactersPositioning": "she kneels between user's legs, giving titjob with her breasts",
      "intimacyLevel": 3
    },
    {
      "location": "poolside",
      "locationDetails": "private villa pool at night",
      "timeOfDay": "night",
      "pose": "standing",
      "activity": "sex in the pool",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she wraps legs around user in the water while he penetrates her",
      "intimacyLevel": 3
    },
    {
      "location": "bedroom",
      "locationDetails": "bedroom with armchair",
      "timeOfDay": "night",
      "pose": "reverse_cowgirl",
      "activity": "intense reverse riding",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she rides user reverse cowgirl on the edge of the bed",
      "intimacyLevel": 3
    },
    {
      "location": "shower",
      "locationDetails": "spacious walk-in shower",
      "timeOfDay": "night",
      "pose": "standing",
      "activity": "shower sex against glass",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she is pressed against the glass wall, user fucking her from behind",
      "intimacyLevel": 3
    },
    {
      "location": "bedroom",
      "locationDetails": "bedroom",
      "timeOfDay": "night",
      "pose": "missionary",
      "activity": "legs over shoulders deep penetration",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she lies on back with legs on user's shoulders, deep intense thrusting",
      "intimacyLevel": 3
    },
    {
      "location": "hotel_room",
      "locationDetails": "luxury hotel room",
      "timeOfDay": "night",
      "pose": "kneeling",
      "activity": "deepthroat blowjob",
      "clothingState": "lingerie",
      "clothingDetails": "garter belt and stockings",
      "charactersPositioning": "she kneels and takes user's entire cock deep in her throat",
      "intimacyLevel": 3
    },
    {
      "location": "living_room",
      "locationDetails": "living room with soft carpet",
      "timeOfDay": "night",
      "pose": "on_all_fours",
      "activity": "doggy style on floor",
      "clothingState": "partially_dressed",
      "clothingDetails": "sweater only, bottom naked",
      "charactersPositioning": "she is on all fours on the carpet, user mounting her from behind",
      "intimacyLevel": 3
    },
    {
      "location": "bedroom",
      "locationDetails": "romantic bedroom",
      "timeOfDay": "night",
      "pose": "sideways",
      "activity": "side sex with leg raised",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she lies on her side with one leg raised high, user penetrating deeply",
      "intimacyLevel": 3
    },
    {
      "location": "bedroom",
      "locationDetails": "bedroom with large bed",
      "timeOfDay": "night",
      "pose": "69",
      "activity": "mutual oral pleasure",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she is on top in 69 position, sucking user while being licked",
      "intimacyLevel": 3
    },
    {
      "location": "balcony",
      "locationDetails": "secluded villa balcony",
      "timeOfDay": "night",
      "pose": "bent_over",
      "activity": "standing doggy on balcony",
      "clothingState": "partially_dressed",
      "clothingDetails": "night slip pulled up",
      "charactersPositioning": "she bends over the balcony table, user taking her from behind",
      "intimacyLevel": 3
    },
    {
      "location": "bedroom",
      "locationDetails": "bedroom",
      "timeOfDay": "night",
      "pose": "missionary",
      "activity": "slow deep passionate sex",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she wraps her arms and legs around user in tight embrace during deep sex",
      "intimacyLevel": 3
    },
    {
      "location": "jacuzzi",
      "locationDetails": "private outdoor jacuzzi at night",
      "timeOfDay": "night",
      "pose": "sitting",
      "activity": "sex in jacuzzi",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she sits on user in the bubbling water, moving up and down",
      "intimacyLevel": 3
    },
    {
      "location": "bedroom",
      "locationDetails": "bedroom",
      "timeOfDay": "night",
      "pose": "kneeling",
      "activity": "handjob and blowjob combo",
      "clothingState": "lingerie",
      "clothingDetails": "sheer black babydoll",
      "charactersPositioning": "she kneels stroking and sucking user's cock",
      "intimacyLevel": 3
    },
    {
      "location": "bedroom",
      "locationDetails": "bedroom with mirror ceiling",
      "timeOfDay": "night",
      "pose": "cowgirl",
      "activity": "riding to orgasm",
      "clothingState": "nude",
      "clothingDetails": null,
      "charactersPositioning": "she rides user intensely, body arched in pleasure, about to climax",
      "intimacyLevel": 3
    }

];