org.gradle.jvmargs=-Xmx4096M -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:ParallelGCThreads=8 -XX:+UseAdaptiveSizePolicy -XX:MaxGCPauseMillis=500 --add-opens=java.base/java.lang.ref=ALL-UNNAMED
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.workers.max=8
org.gradle.configureondemand=true
org.gradle.caching=true

# Kotlin ???????????
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kotlin.parallel.tasks.in.project=true

# Android ???????????
android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=true
android.databinding.incremental=true
android.suppressUnsupportedCompileSdk=35
flutter.minSdkVersion=23
flutter.targetSdkVersion=35
flutter.compileSdkVersion=35
